### ISSUE TITLE
マルチバイト文字を含むURLを投げるとcrashする

### ISSUE THREAD

**Issue by takker99** [ci7lus/ricapitolare#13]
マルチバイト文字を含むURLのOGPを取得しようとすると`500: INTERNAL_SERVER_ERROR`が出てしまいます
- 例：https://ricapitolare.vercel.app/svg?url=https://scrapbox.io/ci7lus/%E3%81%9F%E3%81%AE%E3%81%97%E3%81%84ScrapboxUserScript

axiosがマルチバイト文字も認識できていない？ようです

以下、local serverで試したときのログです
```sh
$ vercel dev
Vercel CLI 24.0.0
> Ready! Available at http://localhost:3000
Unhandled rejection: TypeError: Request path contains unescaped characters
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:154:13)
    at Object.request (node:https:353:10)
    at RedirectableRequest._performRequest (/home/takker/git/ricapitolare/node_modules/follow-redirects/index.js:279:24)
    at new RedirectableRequest (/home/takker/git/ricapitolare/node_modules/follow-redirects/index.js:61:8)
    at Object.request (/home/takker/git/ricapitolare/node_modules/follow-redirects/index.js:487:14)
    at dispatchHttpRequest (/home/takker/git/ricapitolare/node_modules/axios/lib/adapters/http.js:242:25)
    at new Promise (<anonymous>)
    at httpAdapter (/home/takker/git/ricapitolare/node_modules/axios/lib/adapters/http.js:48:10)
    at dispatchRequest (/home/takker/git/ricapitolare/node_modules/axios/lib/core/dispatchRequest.js:58:10) {
  code: 'ERR_UNESCAPED_CHARACTERS'
}
Error! Failed to complete request to /svg?url=https%3A%2F%2Fscrapbox.io%2Fci7lus%2F%E3%81%9F%E3%81%AE%E3%81%97%E3%81%84ScrapboxUserScript: Error: socket hang up
```

**Comment by ci7lus** [comment]
全然気付いてませんでした、ありがとうございました！

**Comment by takker99** [comment]
対応早い！

ありがとうございます！
